definitions:
  entity.Todo:
    properties:
      completed:
        type: boolean
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      description:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
  fiber.Error:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  request.CreateTodoRequest:
    properties:
      description:
        type: string
      title:
        type: string
    required:
    - description
    - title
    type: object
  request.UpdateTodoRequest:
    properties:
      description:
        type: string
      title:
        type: string
    type: object
info:
  contact:
    email: hello@alfredtomo.dev
    name: API Support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
paths:
  /todo:
    get:
      description: get string by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Todo'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Get All Todo's
      tags:
      - todo
    post:
      consumes:
      - application/json
      description: Create a new Todo with the input payload
      parameters:
      - description: Payload for creating a new todo
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateTodoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Todo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Create a new Todo
      tags:
      - todo
  /todo/:id:
    delete:
      consumes:
      - application/json
      description: Delete a Todo with params id
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Delete a Todo
      tags:
      - todo
    patch:
      consumes:
      - application/json
      description: Update a Todo with params id and input payload
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload for creating a new todo
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UpdateTodoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Todo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Update a Todo
      tags:
      - todo
  /todo/:id/complete:
    post:
      consumes:
      - application/json
      description: Complete a Todo with params id
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Todo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Complete a Todo
      tags:
      - todo
swagger: "2.0"
